repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: 
          - pyproject-flake8==0.0.1a2
          - flake8-bugbear==22.1.11
          - flake8-comprehensions==3.8.0
          - flake8_2020==1.6.1
          - mccabe==0.6.1
          - pycodestyle==2.8.0
          - pyflakes==2.4.0

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        additional_dependencies:
          - zigpy==0.43.0

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/fsouza/autoflake8
    rev: v0.3.1
    hooks:
      - id: autoflake8